format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$time\
$line_break\
$character"""

scan_timeout = 10
add_newline = true

[directory]
style="fg:81"
truncation_symbol=".../"

[character]
success_symbol = "[➜](bold fg:39)"
error_symbol = "[✖](bold red)"

[git_status]
style="bold fg:172"

[time]
format="[$time]($style)"
style="bold fg:8"
disabled=false
